GET https://project1-k5sv.onrender.com/Contacts

### Get All Contacts
GET http://localhost:3000/Contacts


###Get contact by id
GET http://localhost:3000/Contacts/6904418d7d449585757e8379


###CREATE CONTACT
POST http://localhost:3000/Contacts HTTP/1.1
content-type: application/json

{
    "firstName": "ddsd",   
    "lastName": "Probando",
    "email": "test@live.com.mx",
    "favoriteColor": "Gray",
    "birthday": "6/May/1970"
  }



### PUT CONTACT
PUT http://localhost:3000/Contacts/690d81c494b58f8b91b50faa HTTP/1.1
content-type: application/json

{
    "firstName": "terceraProve",
    "lastName": "Alanis",
    "email": "anttitest@gmail.com",
    "favoriteColor": "black",
    "birthday": "8/July/2000"
  }


### DELETE Contact
DELETE http://localhost:3000/Contacts/690d82244085a9354a9a3917




###Second array
GET https://project1-k5sv.onrender.com/contacts/690442cb7d449585757e837a

